import type { FieldDefinition, FormPage } from '~/types/form'

export const DEFAULT_PRIMARY_LOGO = '/img/logos/bigidea-logo.svg'

export const PAGE_DEFINITIONS: FormPage[] = [
  {
    key: 'page1',
    title: 'עמוד פתיחה',
    titleFieldKey: '',
    showTitle: false,
    fields: ['mainDescription', 'companyByUserString', 'companyByUserSelect'],
  },
  {
    key: 'camperDetails',
    title: 'פרטי החניך/ה',
    titleFieldKey: 'camperDetailsTitle',
    showTitle: true,
    fields: [
      'camperDetailsMainText',
      'camperFirstName', 'camperLastName',
      'camperFirstNameEn', 'camperLastNameEn',
      'camperAge', 'camperGrade', 'camperGender',
      'camperEmail', 'camperPhone',
      'camperId', 'camperShirt',
      'camperMedicalStatus', 'camperMedicalNotes',
      'camperNutrition',
      'camperDetailsAppendixText',
    ],
  },
  {
    key: 'page2',
    title: 'פרטי ההורה',
    titleFieldKey: 'page2Title',
    showTitle: true,
    fields: [
      'page2MainText',
      'parentFirstName',
      'parentLastName',
      'parentFirstNameEn',
      'parentLastNameEn',
      'parenPhoneNumber',
      'additionalPhoneNumber',
      'parenEmail',
      'additionalParentEmail',
      'workParentEmail',
      'parentId',
      'parentWorkId',
      'page2AppendixText',
    ],
  },
  {
    key: 'page3',
    title: 'בחירת מחזור וסדנאות',
    titleFieldKey: 'page3Title',
    showTitle: true,
    fields: ['page3MainText', 'campLocation', 'campSession', 'campRound', 'Track1', 'Track2', 'TrackAlternative', 'poolApproval', 'friends', 'notes', 'transport', 'photoApproval', 'paymentDeduction', 'page3AppendixText'],
  },
]

export const FIELD_DEFINITIONS: FieldDefinition[] = [
  // ─── Page 1 ───
  {
    key: 'mainDescription',
    label: 'טקסט ראשי',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue:
      '<p style="text-align: center">אנא קראו בתשומת לב את המידע והפירוט על המסלולים השונים באתר לפני מילוי הטופס.</p><p style="text-align: center"><strong>שימו לב</strong> - יש למלא את הטופס בנפרד לכל ילד/ה</p>',
    validation: null,
    options: [],
    page: 'page1',
    isInternalOnly: false,
  },
  {
    key: 'companyByUserString',
    label: 'שם החברה (טקסט)',
    presentationLabel: 'אנא ציינו את החברה בה אתם עובדים',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: 'לדוגמה: גוגל',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page1',
    exclusiveWith: ['companyByUserSelect'],
  },
  {
    key: 'companyByUserSelect',
    label: 'שם החברה (בחירה)',
    presentationLabel: 'אנא ציינו את החברה בה אתם עובדים',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page1',
    exclusiveWith: ['companyByUserString'],
  },

  // ─── Camper Details ───
  {
    key: 'camperDetailsMainText',
    label: 'טקסט ראשי',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
    isInternalOnly: false,
  },
  {
    key: 'camperFirstName',
    label: 'שם פרטי של החניך/ה',
    presentationLabel: 'שם פרטי של החניך/ה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperLastName',
    label: 'שם משפחה של החניך/ה',
    presentationLabel: 'שם משפחה של החניך/ה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperFirstNameEn',
    label: 'שם פרטי של החניך/ה באנגלית',
    presentationLabel: 'שם פרטי של החניך/ה באנגלית',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperLastNameEn',
    label: 'שם משפחה של החניך/ה באנגלית',
    presentationLabel: 'שם משפחה של החניך/ה באנגלית',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperAge',
    label: 'גיל החניך/ה',
    presentationLabel: 'גיל החניך/ה',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: '7', label: '7' },
      { value: '8', label: '8' },
      { value: '9', label: '9' },
      { value: '10', label: '10' },
      { value: '11', label: '11' },
      { value: '12', label: '12' },
      { value: '13', label: '13' },
      { value: '14', label: '14' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperGrade',
    label: 'החניך/ה עולה לכיתה',
    presentationLabel: 'החניך/ה עולה לכיתה',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: 'ב', label: 'ב׳' },
      { value: 'ג', label: 'ג׳' },
      { value: 'ד', label: 'ד׳' },
      { value: 'ה', label: 'ה׳' },
      { value: 'ו', label: 'ו׳' },
      { value: 'ז', label: 'ז׳' },
      { value: 'ח', label: 'ח׳' },
      { value: 'ט', label: 'ט׳' },
      { value: 'י', label: 'י׳' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperGender',
    label: 'מגדר',
    presentationLabel: 'מגדר',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: 'בן', label: 'בן' },
      { value: 'בת', label: 'בת' },
      { value: 'אחר', label: 'אחר' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperEmail',
    label: 'כתובת מייל של החניך/ה',
    presentationLabel: 'כתובת מייל של החניך/ה',
    inputType: 'shortText',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'email',
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperPhone',
    label: 'מספר טלפון של החניך/ה (אופציונלי)',
    presentationLabel: 'מספר טלפון של החניך/ה (אופציונלי)',
    inputType: 'shortText',
    requiredDefault: false,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'israeliPhone',
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperId',
    label: 'מספר ת.ז של החניך/ה',
    presentationLabel: 'מספר ת.ז של החניך/ה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'numbersOnly',
    options: [],
    page: 'camperDetails',
  },
  {
    key: 'camperShirt',
    label: 'מידת חולצה של החניך/ה',
    presentationLabel: 'מידת חולצה של החניך/ה',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: '5', label: '5' },
      { value: '6', label: '6' },
      { value: '8', label: '8' },
      { value: '10', label: '10' },
      { value: '12', label: '12' },
      { value: '14', label: '14' },
      { value: '16', label: '16' },
      { value: '18', label: '18' },
      { value: 'S', label: 'S' },
      { value: 'M', label: 'M' },
      { value: 'L', label: 'L' },
      { value: 'XL', label: 'XL' },
      { value: '2XL', label: '2XL' },
      { value: '3XL', label: '3XL' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperMedicalStatus',
    label: 'מגבלות רפואיות',
    presentationLabel: 'מגבלות רפואיות',
    inputType: 'booleanRadio',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: 'לא ידוע לי על מגבלות רפואיות של החניך/ה', label: 'לא ידוע לי על מגבלות רפואיות של החניך/ה' },
      { value: 'ידוע לי על מגבלות רפואיות של החניך/ה', label: 'ידוע לי על מגבלות רפואיות של החניך/ה' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperMedicalNotes',
    label: 'אנא פרט/י מגבלות רפואיות',
    presentationLabel: 'אנא פרט/י מגבלות רפואיות',
    inputType: 'longText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
    conditionalVisibility: { dependsOn: 'camperMedicalStatus', showWhen: 'positive' },
  },
  {
    key: 'camperNutrition',
    label: 'מגבלות תזונה',
    presentationLabel: 'מגבלות תזונה',
    inputType: 'checkboxOther',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: 'ללא הגבלות', label: 'ללא הגבלות' },
      { value: 'טבעוני/ת', label: 'טבעוני/ת' },
      { value: 'צמחוני/ת', label: 'צמחוני/ת' },
      { value: 'ללא גלוטן', label: 'ללא גלוטן' },
      { value: 'ללא לקטוז', label: 'ללא לקטוז' },
    ],
    page: 'camperDetails',
  },
  {
    key: 'camperDetailsAppendixText',
    label: 'טקסט לפני מעבר לעמוד הבא',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'camperDetails',
    isInternalOnly: false,
  },

  // ─── Page 2: Parent Details ───
  {
    key: 'page2MainText',
    label: 'טקסט ראשי',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
    isInternalOnly: false,
  },
  {
    key: 'parentFirstName',
    label: 'שם פרטי של ההורה',
    presentationLabel: 'שם פרטי של ההורה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
  },
  {
    key: 'parentLastName',
    label: 'שם משפחה של ההורה',
    presentationLabel: 'שם משפחה של ההורה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
  },
  {
    key: 'parentFirstNameEn',
    label: 'שם פרטי של ההורה באנגלית',
    presentationLabel: 'שם פרטי של ההורה באנגלית',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
  },
  {
    key: 'parentLastNameEn',
    label: 'שם משפחה של ההורה באנגלית',
    presentationLabel: 'שם משפחה של ההורה באנגלית',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
  },
  {
    key: 'parenPhoneNumber',
    label: 'טלפון של ההורה',
    presentationLabel: 'טלפון של ההורה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: 'ליצירת קשר',
    placeholder: '',
    defaultValue: '',
    validation: 'israeliPhone',
    options: [],
    page: 'page2',
  },
  {
    key: 'additionalPhoneNumber',
    label: 'טלפון נוסף של ההורה',
    presentationLabel: 'טלפון נוסף של ההורה',
    inputType: 'shortText',
    requiredDefault: false,
    visibleDefault: true,
    infoText: 'ליצירת קשר',
    placeholder: '',
    defaultValue: '',
    validation: 'israeliPhone',
    options: [],
    page: 'page2',
  },
  {
    key: 'parenEmail',
    label: 'כתובת מייל של ההורה',
    presentationLabel: 'כתובת מייל של ההורה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'email',
    options: [],
    page: 'page2',
  },
  {
    key: 'additionalParentEmail',
    label: 'כתובת מייל נוספת של ההורה',
    presentationLabel: 'כתובת מייל נוספת של ההורה ליצירת קשר',
    inputType: 'shortText',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'email',
    options: [],
    page: 'page2',
  },
  {
    key: 'workParentEmail',
    label: 'כתובת מייל במקום העבודה',
    presentationLabel: 'כתובת מייל של ההורה במקום העבודה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: 'יש להזין את כתובת המייל במקום העבודה לצורך זיהוי העובד/ת',
    placeholder: '',
    defaultValue: '',
    validation: 'email',
    options: [],
    page: 'page2',
  },
  {
    key: 'parentId',
    label: 'ת.ז של ההורה',
    presentationLabel: 'מספר ת.ז של ההורה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: 'numbersOnly',
    options: [],
    page: 'page2',
  },
  {
    key: 'parentWorkId',
    label: 'מספר עובד',
    presentationLabel: 'מספר עובד/ת במקום העבודה',
    inputType: 'shortText',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
  },
  {
    key: 'page2AppendixText',
    label: 'טקסט לפני מעבר לעמוד הבא',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page2',
    isInternalOnly: false,
  },

  // ─── Page 3: Camp Location & Session ───
  {
    key: 'page3MainText',
    label: 'טקסט ראשי',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
    isInternalOnly: false,
  },
  {
    key: 'campLocation',
    label: 'מיקום',
    presentationLabel: 'בחרו את המיקום אליו תרצו להירשם',
    inputType: 'radio',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'מקום 1', label: 'מקום 1' }],
    page: 'page3',
  },
  {
    key: 'campSession',
    label: 'מחזור',
    presentationLabel: 'בחרו מחזור',
    inputType: 'radio',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'מחזור 1', label: 'מחזור 1' }],
    page: 'page3',
    fallbackValue: '',
  },
  {
    key: 'campRound',
    label: 'סבב',
    presentationLabel: 'בחרו סבב',
    inputType: 'radio',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'סבב 1', label: 'סבב 1' }],
    page: 'page3',
    fallbackValue: '',
  },
  {
    key: 'Track1',
    label: 'מסלול ראשון',
    presentationLabel: 'בחרו מסלול',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'מסלול 1', label: 'מסלול 1' }],
    page: 'page3',
  },
  {
    key: 'Track2',
    label: 'מסלול שני',
    presentationLabel: 'בחרו מסלול',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'מסלול 1', label: 'מסלול 1' }],
    page: 'page3',
  },
  {
    key: 'TrackAlternative',
    label: 'מסלול אלטרנטיבי',
    presentationLabel: 'בחרו מסלול אלטרנטיבי',
    inputType: 'select',
    requiredDefault: true,
    visibleDefault: true,
    infoText: 'במידה ולא יהיה מקום במסלול שבחרתם או שהוא לא תיפתח.',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [{ value: 'מסלול 1', label: 'מסלול 1' }],
    page: 'page3',
  },
  {
    key: 'poolApproval',
    label: 'אישור כניסה לבריכה',
    presentationLabel: 'אני מאשר/ת לבני/בתי להשתתף בפעילות בריכה',
    inputType: 'radio',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [
      { value: 'מאשר/ת', label: 'מאשר/ת' },
      { value: 'לא מאשר/ת', label: 'לא מאשר/ת' },
    ],
    page: 'page3',
  },
  {
    key: 'friends',
    label: 'חברים שנרשמו',
    presentationLabel: 'חבר/ה שאיתם החניך נרשם ומעוניינים להיות יחד בקבוצה',
    inputType: 'shortText',
    requiredDefault: false,
    visibleDefault: true,
    infoText: 'נא להכניס רק חבר/ה אחת באותו הגיל/כיתה. השיקול יילקח בחשבון במהלך השיבוץ אך לא ניתן להתחייב על שיבוץ לאותה הקבוצה בוודאות.',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
  },
  {
    key: 'notes',
    label: 'הערות',
    presentationLabel: 'הערות נוספות על החניך/ה',
    inputType: 'longText',
    requiredDefault: false,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
  },
  {
    key: 'transport',
    label: 'מעוניין בהסעות',
    presentationLabel: 'אני מעוניין/ת בהסעות לקייטנה עבור החניך/ה',
    inputType: 'toggle',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
    togglePositiveLabel: 'מעוניין/ת',
    toggleNegativeLabel: 'לא מעוניין/ת',
  },
  {
    key: 'photoApproval',
    label: 'אישור שימוש בתמונות',
    presentationLabel: 'אני מאשר/ת שימוש בתמונות הקייטנה לצרכי פרסום הפעילות ברשתות',
    inputType: 'radio',
    requiredDefault: false,
    visibleDefault: true,
    infoText: '',
    placeholder: '',
    defaultValue: 'מאשר/ת',
    validation: null,
    options: [
      { value: 'מאשר/ת', label: 'מאשר/ת' },
      { value: 'לא מאשר/ת', label: 'לא מאשר/ת' },
    ],
    page: 'page3',
  },
  {
    key: 'paymentDeduction',
    label: 'ניכוי תשלום/ימי חופשה',
    presentationLabel: 'מאשר/ת לנכות X ימי חופש עבור הרישום לקייטנה',
    inputType: 'checkbox',
    requiredDefault: true,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
  },
  {
    key: 'page3AppendixText',
    label: 'טקסט לפני מעבר לעמוד הבא',
    presentationLabel: '',
    inputType: 'display',
    requiredDefault: false,
    visibleDefault: false,
    infoText: '',
    placeholder: '',
    defaultValue: '',
    validation: null,
    options: [],
    page: 'page3',
    isInternalOnly: false,
  },
]

export function getDefaultFields(): Record<string, import('~/types/form').FieldConfig> {
  const fields: Record<string, import('~/types/form').FieldConfig> = {}

  for (const def of FIELD_DEFINITIONS) {
    fields[def.key] = {
      key: def.key,
      label: def.label,
      presentationLabel: def.presentationLabel,
      inputType: def.inputType,
      required: def.requiredDefault,
      visible: def.visibleDefault,
      infoText: def.infoText,
      placeholder: def.placeholder,
      defaultValue: def.defaultValue,
      validation: def.validation,
      options: [...def.options],
      ...(def.fallbackValue !== undefined ? { fallbackValue: def.fallbackValue } : {}),
      ...(def.togglePositiveLabel !== undefined ? { togglePositiveLabel: def.togglePositiveLabel } : {}),
      ...(def.toggleNegativeLabel !== undefined ? { toggleNegativeLabel: def.toggleNegativeLabel } : {}),
      ...(def.conditionalVisibility ? { conditionalVisibility: { ...def.conditionalVisibility } } : {}),
    }
  }

  return fields
}

export function getDefaultPages(): FormPage[] {
  return PAGE_DEFINITIONS.map(p => ({
    key: p.key,
    title: p.title,
    titleFieldKey: p.titleFieldKey,
    showTitle: p.showTitle ?? true,
    fields: [...p.fields],
  }))
}

export function getDefaultFormConfig(): Omit<import('~/types/form').FormConfig, '_id' | 'createdAt' | 'updatedAt'> {
  return {
    slug: '',
    formName: 'טופס הרשמה לקייטנת BIGIDEA',
    formTitle: 'טופס הרשמה לקייטנת BIGIDEA',
    company: '',
    primaryLogo: DEFAULT_PRIMARY_LOGO,
    primaryLogoSvgToWhite: false,
    secondaryLogo: null,
    secondaryLogoSvgToWhite: false,
    mainDescription:
      '<p style="text-align: center">אנא קראו בתשומת לב את המידע והפירוט על המסלולים השונים באתר לפני מילוי הטופס.</p><p style="text-align: center"><strong>שימו לב</strong> - יש למלא את הטופס בנפרד לכל ילד/ה</p>',
    campLandingPageUrl: '',
    pages: getDefaultPages(),
    fields: getDefaultFields(),
    isActive: true,
    successTitle: 'הטופס נשלח בהצלחה!',
    successMessage: 'תודה על ההרשמה. נחזור אליכם בהקדם.',
  }
}
